VP_Cam_sensor_width: 23.5
VP_Cam_sensor_height: 15.6
VP_Cam_pixels_horizontal: 6000
VP_Cam_pixels_vertical: 4000
FRAME_WIDTH: 1920
FRAME_HEIGHT: 1080
VIEW_RESIZE: 0.8
CHECKERBOARD_ROWS: 6
CHECKERBOARD_COLUMNS: 9
CHECKERBOARD_SIZE: 35
ARUCO_MARKER_SIZE: 150
ARUCO_MARKER_ID: 8
ARUCO_MODE: Aruco Pose #Camera Pose
show_Calibration_images: False